__commands:

  network:
    - &check_connectivity_by_google_with_ping
      command: >
        ping -n 10 8.8.8.8
  os:
    - &get_current_directory
      command: >
        pwd
  vsc:
    - &git_fetch_current_branch
      command: >
        git fetch origin $(git name-rev --name-only HEAD)

    - &git_pull_current_branch
      command: >
        git pull origin $(git name-rev --name-only HEAD)

    - &git_push_current_branch
      command: >
        git push origin $(git name-rev --name-only HEAD)

  infrastructure:
    - &init
      name: Initialization
      jobs:
        - name: before pipeline
          steps:
            - name: Verify directory - before pipeline
              <<: *get_current_directory
    - &end
      name: End
      jobs:
        - name: after pipeline
          steps:
            - name: Verify directory - after pipeline
              <<: *get_current_directory


pipeline:
  name: Localhost

  stages:

    - *init

    - name: Network
      disable: true
      jobs:
        - name: Network Connectivity
          steps:
            - name: verify google.com
              <<: *check_connectivity_by_google_with_ping
              
    - name: Modules
      jobs:
        - name: Verify package installations
          steps:
            - name: Verify directory - before modules
              <<: *get_current_directory
            - name: verify Git version
              command: git -v

    - name: Git Sync
      jobs:
        - name: Fetch
          steps:
            - name: fetch current branch
              <<: *git_fetch_current_branch
        - name: Pull
          steps:
            - name: pull current branch
              <<: *git_pull_current_branch
        - name: Push
          steps:
            - name: push current branch
              <<: *git_push_current_branch

    - *end
